[package]
name = "atlantis"
version = "0.1.0"
authors = ["=okakyo <=0622okakyo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
