version: "3.7"
services:
    api:
        image: "okakyo/golang-api" 
        security_opt:
            - apparmor:unconfined
        cap_add:
            - SYS_PTRACE
        ports: 
            - 8000:8000